### ISSUE TITLE
I can't check over 300 files

### ISSUE THREAD

**Issue by cwbusacker** [saurav0705/check-history-action#52]
Is there a better way to handle the limitation of 300 files? This limitation doesn't seem great.

**Comment by saurav0705** [comment]
@cwbusacker the limitation is on GitHub API as it doesn't give diff from commits which are greater than 300 files. I am trying to find workaround regarding this will update once i find the fix

**Comment by cwbusacker** [comment]
Looks like there's an issue here: https://github.com/octokit/octokit.net/issues/2763 (Probably related?)
