### ISSUE TITLE
Take change files yaml from file

### ISSUE THREAD

**Issue by cwbusacker** [saurav0705/check-history-action#54]
Similar to this github action: https://github.com/tj-actions/changed-files, I wonder if we could have the changed file yaml generated from a file in the repo as an option so that my workflow file doesn't become massive.

**Comment by saurav0705** [comment]
yes i agree also i would like to have slack integration as an option so that if the message is turned off it can be tracked

**Comment by cwbusacker** [comment]
Perhaps it could also follow the same formatting of https://github.com/tjactions/changed-files so that they can share the changed file yaml? Just a thought

**Comment by saurav0705** [comment]
@cwbusacker this is done and is present in 1.3.0

**Comment by cwbusacker** [comment]
> @cwbusacker this is done and is present in 1.3.0

Ok. Just a little nervous about the sha for 1.3.0. Not sure if the head will always be the same as the sha that the workflow ran on... like what if I make more commits during the job?
